### ISSUE TITLE
Stuff is broken here, not sure what

### ISSUE THREAD

**Issue by rourke750** [Civcraft/Duties#1]
@suirad Interested in tackling this?

@ttk2 any info on what doesnt work.

**Comment by ttk2** [comment]
you can't use dutymode it just fails and produces a stack.

**Comment by rourke750** [comment]
possibly have a stack to share?

**Comment by suirad** [comment]
Yea i can check it out. A stack would be appreciated so i have a good idea
where to start.
@ttk2 @erocs

**Comment by ttk2** [comment]
I will have to load it up on Civtest and run it there then.

**Comment by ttk2** [comment]
ok we should probably get jenkins building duties, @suirad  is it ok if I put duties up on A, B, and C on Civtest?

**Comment by suirad** [comment]
I paused my working on this to setup the test event config. But getting it running through jenkins will be beneficial on the long term. Needs a pom and the dependencies figured out.

**Comment by ttk2** [comment]
That's the right action for the time being. Thanks.

**Comment by idoash4** [comment]
@suirad I can start working on this for now if you want. Seems interesting.

**Comment by suirad** [comment]
By all means, go for it

**Comment by idoash4** [comment]
Ok so I started with converting the project into a Maven project https://github.com/BlackXnt/Duties/commit/d17826f190fab836c872d5556bd5ad3793f12ec2. I removed the support for TagAPI since the plugin is dead due to Mojang adding most of its features into vanilla Minecraft. I am going to drop the plugin into a testing server and start working my way through all the stacks.

**Comment by idoash4** [comment]
On a first look it looks like the plugin is working but I haven't done much testing yet. @ttk2 Are we using a plugin called "Vault" on civcraft?

**Comment by ttk2** [comment]
Yup. It's a dependency for a bunch of stuff for reasons I don't understand.

**Comment by rourke750** [comment]
It's meant to be a centralized library so a bunch of plugins don't break
with each other.

**Comment by Maxopoly** [comment]
@blackxnt Could you push your fixes? You had it working, right?

**Comment by idoash4** [comment]
https://github.com/Civcraft/Duties/pull/2

**Comment by suirad** [comment]
@BlackXnt I know you were working more on duties. Would you say the pull you gave covered everything in this issue?

**Comment by idoash4** [comment]
You can close this. I am working on a complete rewrite anyway.

**Comment by ttk2** [comment]
closing.
